#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#   - Listens on port 80.
#   - Returns a page containing "Hello World!" when queried
#     at the root with a curl GET request.
#   - /redirect_me is redirecting to another page

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow Nginx HTTP through the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership of website files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create new index
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Setting up /redirect_me
sudo sed -i '/^\s*location \/ {$/a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx

